### ISSUE TITLE
보안과 성능 관련 건의

### ISSUE THREAD

**Issue by KH-CHOO** [innovationCamp/messenger-service#45]
https://stackoverflow.com/questions/46112865/bcryptpasswordencoder-seems-resource-consuming-a-lot
https://stackoverflow.com/questions/51777464/why-is-spring-boot-security-basic-authentication-slow

패스워드 인코딩이 리소스를 상당히 많이 잡아먹는다고 알고 있습니다.
로그인과 보안 쪽을 주요 목표로 다루는 것이 아니라면 
차라리 패스워드 인코딩을 빼는 것은 어떨까 생각이 드는데 다들 어떠신가요.

물론 쌩으로 DB에 비밀번호를 넣는 것 자체는 말도 안되는 상황이지만, 
보안도 챙기고 성능도 보장하기가 어렵지는 않을까 해서 의견 남깁니다.

추가)
이 부분을 챌린징 포인트로 생각해 볼 수도 있을 것 같기는 합니다.
개인적으로는 우선순위 달성 후 추가로 고려해 보면 좋을 것 같은 부분이라고 생각합니다.

**Comment by cornpip** [comment]
bcrypto가 무겁다면 적당한 해시/암호화 알고리즘 구현 또는 라이트한 라이브러리를 고려할 수 있을 것 같습니다. 패스워드 암호화가 가져가는 리소스를 암호화를 포기하며 줄일 이유는 없을 것 같아요

**Comment by KH-CHOO** [comment]
> bcrypto가 무겁다면 적당한 해시 알고리즘 구현 또는 라이트한 라이브러리를 고려할 수 있을 것 같습니다. 패스워드 암호화가 가져가는 리소스를 암호화를 포기하며 줄일 이유는 없을 것 같아요

적당한 해시 알고리즘 또는 라이트한 라이브러리를 추가하는 것이 보안에 도움이 되는가 생각해 보면 그렇지 않을것 같아서요..
없는 것과 별로 차이가 없다고 생각합니다.

**Comment by cornpip** [comment]
암호화를 어떻게 구현하는가에 따라 다를 것 같네요. 라이트한 라이브러리를 사용한다해도 쓰임새가 있으니까 사용될 수 있을테고 일단 챌린징 포인트는 보안에 가까워 보여요
